name: Run Tests with Hypothesis

on:
  push:
    branches:
      - main  # or the default branch you want
  pull_request:
    branches:
      - main  # or the default branch you want

jobs:
  test:
    runs-on: ubuntu-22.04  # or any appropriate runner for your setup
    
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -t hypothesis-tests .

      # Step 4: Run tests in the container
      - name: Run tests
        run: |
          docker run --rm hypothesis-tests
